<table id="tablaentidades" class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>NRO</th>
        <th>RUC/DNI</th>
        <th>NOMBRE</th>
        <th>REPRESENTANTE</th>
        <th>CORREO</th>
        <th>TELEFONO</th>
        <th>DIRECCION</th>
        <th>TIPO</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tfoot>
      <tr>
        <th>NRO</th>
        <th>RUC/DNI</th>
        <th>NOMBRE</th>
        <th>REPRESENTANTE</th>
        <th>CORREO</th>
        <th>TELEFONO</th>
        <th>DIRECCION</th>
        <th>TIPO</th>
        <th>Acciones</th>
      </tr>
    </tfoot>
  </table>